services:
  - type: web
    name: siemens-dishwasher-scheduler
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_URL
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: DATA_DIR
        value: /var/data
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
